# Generated by Django 5.0.7 on 2024-07-24 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OriginAdresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='RealEstate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=256, unique=True)),
                ('title', models.CharField(max_length=128)),
                ('price', models.CharField(max_length=50)),
                ('coordinates', models.CharField(max_length=50)),
                ('specs_dict', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='RealEstateOriginDistances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.TimeField()),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.realestate')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.originadresses')),
            ],
        ),
    ]
